name: Setup Windows Server on GitHub Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-windows-server:
    runs-on: windows-latest  # Use GitHub-hosted Windows runner
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Verify Python Installation
        run: python --version

      - name: Install RustDesk from Repo
        run: |
          $installerPath = "${{ github.workspace }}\rustdesk.exe"

          if (Test-Path $installerPath) {
              Write-Host "Found RustDesk installer, proceeding with installation..."
              Start-Process -FilePath $installerPath -ArgumentList "/verysilent /norestart" -NoNewWindow -Wait
          } else {
              Write-Host "❌ RustDesk installer not found!"
              exit 1
          }
        shell: powershell

      - name: Verify RustDesk Installation
        run: |
          if (Test-Path "C:\Program Files\RustDesk\RustDesk.exe") {
              Write-Host "✅ RustDesk installed successfully!"
          } else {
              Write-Host "❌ RustDesk installation failed."
              exit 1
          }
        shell: powershell
