name: Windows Server Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-windows-server:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Python 3.10
        run: |
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.10.11/python-3.10.11-amd64.exe" -OutFile "python-installer.exe"
          Start-Process -FilePath "python-installer.exe" -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -NoNewWindow -Wait
          Remove-Item -Force "python-installer.exe"

      - name: Verify Python Installation
        run: python --version

      - name: Install RustDesk
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/latest/download/RustDesk-Windows.zip" -OutFile "RustDesk.zip"
          Expand-Archive -Path "RustDesk.zip" -DestinationPath "RustDesk"
          Remove-Item -Force "RustDesk.zip"

      - name: Verify RustDesk Installation
        run: Get-ChildItem -Path "RustDesk"
